"""add auction date to filterpreset

Revision ID: 8aa59c24587b
Revises: 7b3643c997c4
Create Date: 2025-09-29 21:04:24.380179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aa59c24587b'
down_revision: Union[str, Sequence[str], None] = '7b3643c997c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_preset', sa.Column('auction_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_preset', 'auction_date')
    # ### end Alembic commands ###
